### ISSUE TITLE
Removal of AquaLickX

### ISSUE THREAD

**Issue by bcarrington** [VisualisationExpo/AquaLickX-Sonoma145Edition#4]
Hi! This is great, but just wanted to make sure if I ever wanted to remove this. I assume I would just want to livemount the system volume, remove those .car files, and then bless?

**Comment by VisualisationExpo** [comment]
Thank you for the praise.

Don't remove / delete the .car files. You should keep a backup of the original .car files. Preferably all of them.


### Proceed with the following

1. Mount your drive to `livemount` as before.
2. Copy in your backup files of all the .car files used in this AquaLickX theme.
3. Use the bless command to bless your drive one last time.
4. Reboot.  

**Deleting APFS bless snapshots**
When you decide it's best to enable SIP fully again, then I would encourage your to delete the APFS bless snapshots that are made because of this.

Essentially you could just leave the snapshots there if you've returned to a non-AquaLickX state but wish to have SIP disabled. I usually delete them after the fact.
 
*This here is from my recovery partition where you'll see an APFS snapshot I made earlier today to illustrate the bless snapshots to be deleted after you've enabled SIP. You can't delete this while authenticated-root is disabled and SIP is disabled. 
You'll have to do this only after you've reinstated the original .car files (e.g macOS Sonoma's .car files) and SIP is fully enabled as to not confuse the OS and prevent your Mac from booting*

**leave the system snapshot be. To my knowledge you can't delete this. But just don't try**
  
![IMG_0508 2](https://github.com/user-attachments/assets/4e2a525c-a71c-45d8-975a-4ebefd496d8d)

**Comment by VisualisationExpo** [comment]
This is all very risky, and luckily there's a newer theming option for macOS on the block that doesn't require the use of bless commands, but still require SIP off (we'll never get around this I don't think)
I'm working on bringing an old theme called Niqu to this platform.

I haven't ported AquaLickX to this platform.. seems rather obvious that I do, but that's just a me problem. 

the platform is very new and scary, but no mounting of volumes is a plus

The lack of updates to this AquaLickX theme is a consequence of the other theming option coming to market (Discord)
![Screenshot 2024-09-23 at 11 09 34](https://github.com/user-attachments/assets/7081bce5-ac95-4d9a-8b55-70320aba30fb)

**Comment by Meowmew124** [comment]
> Thank you for the praise.
> 
> Don't remove / delete the .car files. You should keep a backup of the original .car files. Preferably all of them.
> ### Proceed with the following
> 
>     1. Mount your drive to `livemount` as before.
> 
>     2. Copy in your backup files of all the .car files used in this AquaLickX theme.
> 
>     3. Use the bless command to bless your drive one last time.
> 
>     4. Reboot.
> 
> 
> **Deleting APFS bless snapshots** When you decide it's best to enable SIP fully again, then I would encourage your to delete the APFS bless snapshots that are made because of this.
> 
> Essentially you could just leave the snapshots there if you've returned to a non-AquaLickX state but wish to have SIP disabled. I usually delete them after the fact.
> 
> _This here is from my recovery partition where you'll see an APFS snapshot I made earlier today to illustrate the bless snapshots to be deleted after you've enabled SIP. You can't delete this while authenticated-root is disabled and SIP is disabled. You'll have to do this only after you've reinstated the original .car files (e.g macOS Sonoma's .car files) and SIP is fully enabled as to not confuse the OS and prevent your Mac from booting_
> 
> **leave the system snapshot be. To my knowledge you can't delete this. But just don't try**
> 
> ![IMG_0508 2](https://private-user-images.githubusercontent.com/86615159/369806534-4e2a525c-a71c-45d8-975a-4ebefd496d8d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNTc5MzksIm5iZiI6MTcyOTA1NzYzOSwicGF0aCI6Ii84NjYxNTE1OS8zNjk4MDY1MzQtNGUyYTUyNWMtYTcxYy00NWQ4LTk3NWEtNGViZWZkNDk2ZDhkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQwNTQ3MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGI1ZGYzMGZmZWY0MmE3MjZmM2Y1MjQ1YzIyNGMzNzg1YjhjNWM4Y2FlYmFlZDk1YjZiZDg3NTJkMTIwYjRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IC7hrQ_i75nxd-4npiITZnD7QOHCjDqB1grWA6eAn2Q)

So like, after I did your steps to uninstalling the theme, it didn't go. I tried clearing its caches, no use. Any other way of removing the theme?

**Comment by VisualisationExpo** [comment]
The way is to use your backup files of the car files

You should have those on hand and copy them in the same way AquaLickX files are copied in

Then use the bless command once again. Reboot and you have the original theme back

When you decide to reinstate SIP after this you'll of course get your original macOS theme back

Should you decide to open for file access again you'll. Have your original theme because you copied the files in and blessed those files before you enabled SIP again

There's no real hocus pokus to it.

**Comment by VisualisationExpo** [comment]
check out this repo here : https://github.com/VisualisationExpo/Uninstalling-my-themes/blob/main/README.md
